rabbitmq:
  image: "rabbitmq:3-management"
  environment:
    RABBITMQ_ERLANG_COOKIE: "KOW5OQEFvEJfHR5YUKqa2yFYe0fupZ8A"
    RABBITMQ_DEFAULT_USER: "rabbitmq"
    RABBITMQ_DEFAULT_PASS: "rabbitmq"
    RABBITMQ_DEFAULT_VHOST: "/"
  ports:
    - "15672:15672"
    - "5672:5672"
